### ISSUE TITLE
Change plugin name from 'cz.malohlava' to 'cz.malohlava.visteg'

### ISSUE THREAD

**Issue by leonard84** [mmalohlava/gradle-visteg#11]
I would suggest to change the plugin name from 'cz.malohlava' to 'cz.malohlava.visteg' to be in line with other plugin names. https://plugins.gradle.org/plugin/cz.malohlava

The current readme also suggest this naming, which doesn't work at the moment.

```
plugins {
  id 'cz.malohlava.visteg' version '1.0.3'
}
```

**Comment by mmalohlava** [comment]
Use versin 1.0.5: https://plugins.gradle.org/plugin/cz.malohlava.visteg
