### ISSUE TITLE
Fix usage instructions

### ISSUE THREAD

**Issue by tux-mind** [mmalohlava/gradle-visteg#5]
Please fix the **Apply visteg plugin** section of the readme.

give a look to the [official gradle plugin website](https://plugins.gradle.org/plugin/cz.malohlava) to take correct statements.

Thank you for your work :blush:

**Comment by mmalohlava** [comment]
Thank you!

I think this looks now pretty standard:
https://plugins.gradle.org/plugin/cz.malohlava.visteg
